# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Heroku Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.0.4
      with:
        node-version: ${{ matrix.node-version }}
        heroku_api_key: 444f1b88-588a-4094-b995-bcf53a881656
        # Email that you use with heroku
        heroku_email: mhmd2sheik@gmail.com
        # The appname to use for deploying/updating
        heroku_app_name: todo-react-app-new
